# Homebrew Taps
tap "homebrew/services"
tap "jandedobbeleer/oh-my-posh"

# Development Tools
brew "borders"
brew "entr"
brew "fastfetch"
brew "ffmpeg"
brew "fswatch"
brew "lua"
brew "mas"
brew "neovim"
brew "node"
brew "npm"
brew "oh-my-posh"
brew "sketchybar"
brew "switchaudio-osx"
brew "watch"
brew "yt-dlp"

# GUI Applications
cask "aerospace"
cask "alacritty"
cask "appcleaner"
cask "blockstream"
cask "brave-browser"
cask "claude"
cask "cursor"
cask "devcleaner"
cask "discord"
cask "ente-auth"
cask "fantastical"
cask "flux-app"
cask "ghostty"
cask "google-chrome"
cask "hiddenbar"
cask "karabiner-elements"
cask "keka"
cask "obsidian"
cask "plex"
cask "postman"
cask "pronotes"
cask "proton-pass"
cask "proxyman"
cask "raycast"
cask "rocket"
cask "sf-symbols"
cask "slack"
cask "spotify"
cask "synologyassistant"
cask "tailscale-app"
cask "telegram"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "xcodes-app"
cask "xld"
cask "zed"
cask "zen"
cask "zoom"

# Fonts
cask "font-caskaydia-cove-nerd-font"
cask "font-hack-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-sf-mono"

# Mac App Store Applications
mas "Amphetamine", id: 937984704
mas "TestFlight", id: 899247664
